"""empty message

Revision ID: 17dafccf7c38
Revises: a30edf5131c6
Create Date: 2021-06-19 17:13:39.358197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17dafccf7c38'
down_revision = 'a30edf5131c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_chart_of_account')
    with op.batch_alter_table('chart_of_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sum_account', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_posting_account')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_of_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_posting_account', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('is_sum_account')

    op.create_table('_alembic_tmp_chart_of_account',
    sa.Column('account_code', sa.INTEGER(), nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=1), nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('account_description', sa.TEXT(), nullable=True),
    sa.Column('is_sum_account', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('account_code', name='pk_chart_of_account'),
    sa.UniqueConstraint('account_name', name='uq_chart_of_account_account_name')
    )
    # ### end Alembic commands ###
