"""empty message

Revision ID: 492663038eb4
Revises: 17dafccf7c38
Create Date: 2021-06-19 18:27:45.057385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492663038eb4'
down_revision = '17dafccf7c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_of_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_group', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_of_account', schema=None) as batch_op:
        batch_op.drop_column('account_group')

    # ### end Alembic commands ###
