"""empty message

Revision ID: 71c6c7fe272e
Revises: 492663038eb4
Create Date: 2021-06-22 00:34:40.978082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c6c7fe272e'
down_revision = '492663038eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_type', sa.String(length=1), nullable=False))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.String(length=1), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('document_type')

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_column('partner_type')

    # ### end Alembic commands ###
