"""empty message

Revision ID: a30edf5131c6
Revises: a561309f6e8d
Create Date: 2021-06-19 16:12:59.970717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30edf5131c6'
down_revision = 'a561309f6e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_of_account', schema=None) as batch_op:
        batch_op.drop_column('account_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_of_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_group', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
